delete from ipa_expedient_interessat;
delete from ipa_interessat;
delete from ipa_cont_log;
delete from ipa_document_versio;
delete from ipa_document;
delete from ipa_expedient;
delete from ipa_carpeta;
delete from ipa_dada;
delete from ipa_node;
delete from ipa_escriptori;
update ipa_contenidor set contmov_id=null;
delete from ipa_cont_mov;
delete from ipa_registre;
delete from ipa_registre_doc;
delete from ipa_registre_inter;
delete from ipa_arxiu;
delete from ipa_bustia;
delete from ipa_contenidor where pare_id is null;
delete from ipa_contenidor where pare_id is null;
delete from ipa_contenidor where pare_id is null;
delete from ipa_contenidor;