
CREATE OR REPLACE TRIGGER IPA_ACLCLA_IDGEN_TRG
BEFORE INSERT ON IPA_ACL_CLASS
FOR EACH ROW
  BEGIN
    SELECT IPA_ACL_CLASS_SEQ.NEXTVAL INTO :new.id FROM dual;
  END;
/
SHOW ERRORS;
 
CREATE OR REPLACE TRIGGER IPA_ACLENT_IDGEN_TRG
BEFORE INSERT ON IPA_ACL_ENTRY
FOR EACH ROW
  BEGIN
    SELECT IPA_ACL_ENTRY_SEQ.NEXTVAL INTO :new.id FROM dual;
  END;
/
SHOW ERRORS;
 
CREATE OR REPLACE TRIGGER IPA_ACLOID_IDGEN_TRG
BEFORE INSERT ON IPA_ACL_OBJECT_IDENTITY
FOR EACH ROW
  BEGIN
    SELECT IPA_ACL_OBJECT_IDENTITY_SEQ.NEXTVAL INTO :new.id FROM dual;
  END;
/
SHOW ERRORS;
 
CREATE OR REPLACE TRIGGER IPA_ACLSID_IDGEN_TRG
BEFORE INSERT ON IPA_ACL_SID
FOR EACH ROW
  BEGIN
    SELECT IPA_ACL_SID_SEQ.NEXTVAL INTO :new.id FROM dual;
  END;
/
SHOW ERRORS;
