ALTER TABLE IPA_METADOCUMENT MOVE LOB (PLANTILLA_CONTINGUT) STORE AS IPA_METADOC_PLANTILLA_LOB (TABLESPACE RIPEA_LOB);
ALTER TABLE IPA_DOCUMENT MOVE LOB (FITXER_CONTINGUT) STORE AS IPA_DOCUME_FITXER_LOB (TABLESPACE RIPEA_LOB);
