ALTER TABLE IPA_METADOCUMENT MOVE LOB (PLANTILLA_CONTINGUT) STORE AS IPA_METADOC_PLANTILLA_LOB (TABLESPACE RIPEA_LOB);
ALTER TABLE IPA_DOCUMENT_VERSIO MOVE LOB (ARXIU_CONTINGUT) STORE AS IPA_DOCVER_ARXIU_LOB (TABLESPACE RIPEA_LOB);


