DELETE FROM IPA_EXPEDIENT_INTERESSAT;
DELETE FROM IPA_INTERESSAT;

ALTER TABLE IPA_INTERESSAT
	MODIFY ( NOM VARCHAR2(30 CHAR) ) 
	MODIFY ( IDENTIFICADOR VARCHAR2(80 CHAR) ) 
	ADD ( DOCUMENT_TIPUS VARCHAR2(40) NOT NULL  ) 
	ADD ( DOCUMENT_NUM VARCHAR2(17) NOT NULL  ) 
	ADD ( PAIS VARCHAR2(4) NULL  ) 
	ADD ( PROVINCIA VARCHAR2(2) NULL  ) 
	ADD ( MUNICIPI VARCHAR2(5) NULL  ) 
	ADD ( ADRESA VARCHAR2(160) NULL  ) 
	ADD ( CODI_POSTAL VARCHAR2(5) NULL  ) 
	ADD ( EMAIL VARCHAR2(160) NULL  ) 
	ADD ( TELEFON VARCHAR2(20) NULL  ) 
	ADD ( OBSERVACIONS VARCHAR2(160) NULL  ) 
	ADD ( NOT_IDIOMA VARCHAR2(2) NULL  ) 
	ADD ( NOT_AUTORITZAT NUMBER(1) NOT NULL  ) 
	ADD ( IDENTIFICADOR VARCHAR2(80) NULL  ) 
	ADD ( EXPEDIENT_ID NUMBER(19) NOT NULL  ) 
	ADD ( REPRESENTANT_ID NUMBER(19) NULL  ) 
	ADD ( LLINATGE1 VARCHAR2(30) NULL  ) 
	ADD ( LLINATGE2 VARCHAR2(30) NULL  ) 
	ADD ( ORGAN_CODI VARCHAR2(9) NULL  ) 
	ADD ( RAO_SOCIAL VARCHAR2(80) NULL  )
	ADD ( ES_REPRESENTANT NUMBER(1) NOT NULL  );
	
	
ALTER TABLE IPA_INTERESSAT DROP CONSTRAINT IPA_INTERESSAT_MULT_UK;
ALTER TABLE IPA_INTERESSAT ADD CONSTRAINT IPA_INTERESSAT_MULT_UK UNIQUE (ENTITAT_ID, EXPEDIENT_ID, DOCUMENT_NUM, NOM, LLINATGE1, LLINATGE2, RAO_SOCIAL, ORGAN_CODI);

ALTER TABLE IPA_INTERESSAT ADD CONSTRAINT IPA_EXPEDIENT_INTERESSAT_FK FOREIGN KEY (EXPEDIENT_ID) REFERENCES IPA_EXPEDIENT (ID);
ALTER TABLE IPA_INTERESSAT ADD CONSTRAINT IPA_INTERESSAT_INTERESSAT_FK FOREIGN KEY (REPRESENTANT_ID) REFERENCES IPA_INTERESSAT (ID");

