CREATE SEQUENCE hibernate_sequence
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    MAXVALUE 999999999999999999
    CACHE 20;


CREATE SEQUENCE IPA_ACL_CLASS_SEQ
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

ALTER SEQUENCE IPA_ACL_CLASS_SEQ OWNED BY IPA_ACL_CLASS.id;

CREATE SEQUENCE IPA_ACL_ENTRY_SEQ
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

ALTER SEQUENCE IPA_ACL_ENTRY_SEQ OWNED BY IPA_ACL_ENTRY.id;

CREATE SEQUENCE IPA_ACL_OBJECT_IDENTITY_SEQ
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

ALTER SEQUENCE IPA_ACL_OBJECT_IDENTITY_SEQ OWNED BY IPA_ACL_OBJECT_IDENTITY.id;

CREATE SEQUENCE IPA_ACL_SID_SEQ
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

ALTER SEQUENCE IPA_ACL_SID_SEQ OWNED BY IPA_ACL_SID.id;
