
package es.caib.notib.ws.notificacio;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b14002
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "NotificacioWsServiceException", targetNamespace = "http://www.caib.es/notib/ws/notificacio")
public class NotificacioWsServiceException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private NotificacioWsServiceException faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public NotificacioWsServiceException_Exception(String message, NotificacioWsServiceException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public NotificacioWsServiceException_Exception(String message, NotificacioWsServiceException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: es.caib.notib.ws.notificacio.NotificacioWsServiceException
     */
    public NotificacioWsServiceException getFaultInfo() {
        return faultInfo;
    }

}
