-----------------------------------------------------------------
-- 	#155: Poder ordenar bústies per nom d'unitat organitzat
-----------------------------------------------------------------
-----------------------------------------------------------------
-- 	#165: Gestió i Sincronització de UO
-----------------------------------------------------------------

CREATE TABLE IPA_UNITAT_ORGANITZATIVA (
  ID           				BIGINT          NOT NULL,
  CODI 						CHARACTER VARYING(9) 		NOT NULL,
  DENOMINACIO 				CHARACTER VARYING(300) 		NOT NULL,
  NIF_CIF 					CHARACTER VARYING(9),
  CODI_UNITAT_SUPERIOR 		CHARACTER VARYING(9),
  CODI_UNITAT_ARREL 		CHARACTER VARYING(9),
  DATA_CREACIO_OFICIAL 		TIMESTAMP WITHOUT TIME ZONE,
  DATA_SUPRESSIO_OFICIAL 	TIMESTAMP WITHOUT TIME ZONE,
  DATA_EXTINCIO_FUNCIONAL 	TIMESTAMP WITHOUT TIME ZONE,
  DATA_ANULACIO 	 		TIMESTAMP WITHOUT TIME ZONE,
  ESTAT 					BOOLEAN,
  CODI_PAIS 				CHARACTER VARYING(3),
  CODI_COMUNITAT 			CHARACTER VARYING(2),
  CODI_PROVINCIA 			CHARACTER VARYING(2),
  CODI_POSTAL 				CHARACTER VARYING(5),
  NOM_LOCALITAT 			CHARACTER VARYING(50),
  LOCALITAT 				CHARACTER VARYING(40),
  ADRESSA 					CHARACTER VARYING(70),
  TIPUS_VIA 	 			BIGINT,
  NOM_VIA 					CHARACTER VARYING(200),
  NUM_VIA 					CHARACTER VARYING(100),
  TIPUS_TRANSICIO 		    INTEGER,

  CREATEDDATE          		TIMESTAMP WITHOUT TIME ZONE,
  CREATEDBY_CODI       		CHARACTER VARYING(256),
  LASTMODIFIEDDATE     		TIMESTAMP WITHOUT TIME ZONE,
  LASTMODIFIEDBY_CODI  		CHARACTER VARYING(256)
);
ALTER TABLE IPA_UNITAT_ORGANITZATIVA ADD CONSTRAINT IPA_UNITAT_ORGANITZATIVA_PK PRIMARY KEY (ID);
  
 
ALTER TABLE IPA_BUSTIA ADD UNITAT_ID BIGINT;
ALTER TABLE IPA_BUSTIA ADD CONSTRAINT IPA_UNITAT_BUSTIA_FK FOREIGN KEY (UNITAT_ID) REFERENCES IPA_UNITAT_ORGANITZATIVA (ID);
    
    
ALTER TABLE IPA_REGLA ADD UNITAT_ID BIGINT;
ALTER TABLE IPA_REGLA ADD CONSTRAINT IPA_UNITAT_REGLA_FK FOREIGN KEY (UNITAT_ID) REFERENCES IPA_UNITAT_ORGANITZATIVA (ID);
    
    
CREATE TABLE IPA_UO_SINC_REL (
  ANTIGA_UO         			BIGINT          NOT NULL,
  NOVA_UO           			BIGINT          NOT NULL
);
ALTER TABLE IPA_UO_SINC_REL ADD CONSTRAINT IPA_UNITAT_ANTIGA_FK FOREIGN KEY (ANTIGA_UO) REFERENCES IPA_UNITAT_ORGANITZATIVA (ID);
ALTER TABLE IPA_UO_SINC_REL ADD CONSTRAINT IPA_UNITAT_NOVA_FK FOREIGN KEY (NOVA_UO) REFERENCES IPA_UNITAT_ORGANITZATIVA (ID);
ALTER TABLE IPA_UO_SINC_REL ADD CONSTRAINT IPA_UO_SINC_REL_MULT_UK UNIQUE (ANTIGA_UO, NOVA_UO);


ALTER TABLE IPA_ENTITAT 
	ADD FECHA_ACTUALIZACION TIMESTAMP WITHOUT TIME ZONE 
	ADD FECHA_SINCRONIZACION TIMESTAMP WITHOUT TIME ZONE;  
	
	
	
	
UPDATE IPA_BUSTIA SET UNITAT_ID = (SELECT ID FROM IPA_UNITAT_ORGANITZATIVA WHERE CODI = IPA_BUSTIA.UNITAT_CODI);
   
UPDATE IPA_REGLA SET UNITAT_ID = (SELECT ID FROM IPA_UNITAT_ORGANITZATIVA WHERE CODI = IPA_REGLA.UNITAT_CODI);
