CREATE TABLE IPA_ALERTA
(
  ID                   BIGINT                          NOT NULL,
  TEXT                 character varying(256)          NOT NULL,
  ERROR                character varying(2048),
  LLEGIDA              boolean                         NOT NULL,
  CONTINGUT_ID         bigint,
  CREATEDBY_CODI       character varying(64),
  CREATEDDATE          timestamp without time zone,
  LASTMODIFIEDBY_CODI  character varying(64),
  LASTMODIFIEDDATE     timestamp without time zone
);

ALTER TABLE ONLY IPA_ALERTA ADD CONSTRAINT IPA_ALERTA_PK PRIMARY KEY (ID);
ALTER TABLE ONLY IPA_ALERTA ADD CONSTRAINT IPA_CONTINGUT_ALERTA_FK FOREIGN KEY (CONTINGUT_ID) REFERENCES IPA_CONTINGUT (ID);
ALTER TABLE ONLY IPA_ALERTA ADD CONSTRAINT IPA_USUCRE_ALERTA_FK FOREIGN KEY (CREATEDBY_CODI) REFERENCES IPA_USUARI (CODI);
ALTER TABLE ONLY IPA_ALERTA ADD CONSTRAINT IPA_USUMOD_ALERTA_FK FOREIGN KEY (LASTMODIFIEDBY_CODI) REFERENCES IPA_USUARI (CODI);

CREATE INDEX IPA_CONTINGUT_ALERTA_FK_I ON IPA_ALERTA(CONTINGUT_ID);
CREATE INDEX IPA_USUCRE_ALERTA_FK_I ON IPA_ALERTA(CREATEDBY_CODI);
CREATE INDEX IPA_USUMOD_ALERTA_FK_I ON IPA_ALERTA(LASTMODIFIEDBY_CODI);
