-----------------------------------------------------------------
-- #144 Millora. Modificacio de enviament de emails als usuaris
-----------------------------------------------------------------
CREATE TABLE IPA_CONT_MOV_EMAIL 
(
  ID 					BIGINT 					NOT NULL, 
  DESTINATARI_CODI		character varying(64) 	NOT NULL, 
  DESTINATARI_EMAIL		character varying(256) 	NOT NULL,
  ENVIAMENT_AGRUPAT		boolean					NOT NULL,
  BUSTIA_ID 			BIGINT 					NOT NULL,
  CONTINGUT_MOVIMENT_ID BIGINT 					NOT NULL, 
  CONTINGUT_ID 			BIGINT 					NOT NULL,
  UNITAT_ORGANITZATIVA 	character varying(256),
  CREATEDDATE          	timestamp without time zone,
  LASTMODIFIEDDATE     	timestamp without time zone,
  CREATEDBY_CODI       	character varying(64),
  LASTMODIFIEDBY_CODI  	character varying(64)
);

ALTER TABLE ONLY IPA_CONT_MOV_EMAIL ADD CONSTRAINT IPA_CONT_MOV_EMAIL_PK PRIMARY KEY (ID);
ALTER TABLE ONLY IPA_CONT_MOV_EMAIL ADD CONSTRAINT IPA_BUSTIA_CONTMOVEMAIL_FK FOREIGN KEY (BUSTIA_ID) REFERENCES IPA_BUSTIA (ID);
ALTER TABLE ONLY IPA_CONT_MOV_EMAIL ADD CONSTRAINT IPA_CONTMOV_CONTMOVEMAIL_FK FOREIGN KEY (CONTINGUT_MOVIMENT_ID) REFERENCES IPA_CONT_MOV (ID);
ALTER TABLE ONLY IPA_CONT_MOV_EMAIL ADD CONSTRAINT IPA_CONT_CONTMOVEMAIL_FK FOREIGN KEY (CONTINGUT_ID) REFERENCES IPA_CONTINGUT (ID);

CREATE INDEX IPA_DEST_CONTMOVEMAIL_FK_I ON IPA_CONT_MOV_EMAIL(DESTINATARI_CODI);

ALTER TABLE IPA_USUARI ADD REBRE_EMAILS boolean;
ALTER TABLE IPA_USUARI ADD EMAILS_AGRUPATS boolean;

UPDATE IPA_USUARI SET REBRE_EMAILS = true WHERE REBRE_EMAILS IS NULL;
UPDATE IPA_USUARI SET EMAILS_AGRUPATS = true WHERE EMAILS_AGRUPATS IS NULL;

