CREATE TABLE IPA_REGISTRE_ANNEX_FIRMA
(
  ID                   BIGINT                   	NOT NULL,
  TIPUS		           character varying(30),
  PERFIL    	       character varying(30),
  FITXER_NOM           character varying(80),
  TIPUS_MIME           character varying(30),
  CSV_REGULACIO		   character varying(640),
  ANNEX_ID             bigint(19)               	NOT NULL,
  CREATEDDATE          timestamp without time zone,
  CREATEDBY_CODI       character varying(256),
  LASTMODIFIEDDATE     timestamp without time zone,
  LASTMODIFIEDBY_CODI  character varying(256)
);

ALTER TABLE ONLY IPA_REGISTRE_ANNEX_FIRMA ADD CONSTRAINT IPA_REGANXFIR_PK PRIMARY KEY (ID);  

ALTER TABLE IPA_REGISTRE_ANNEX_FIRMA ADD CONSTRAINT IPA_USUCRE_REGANXFIR_FK FOREIGN KEY (CREATEDBY_CODI) REFERENCES IPA_USUARI (CODI);
ALTER TABLE IPA_REGISTRE_ANNEX_FIRMA ADD CONSTRAINT IPA_FIRMA_ANNEX_FK FOREIGN KEY (ANNEX_ID) REFERENCES IPA_REGISTRE_ANNEX (ID);
ALTER TABLE IPA_REGISTRE_ANNEX_FIRMA ADD CONSTRAINT IPA_USUMOD_REGANXFIR_FK FOREIGN KEY (LASTMODIFIEDBY_CODI) REFERENCES IPA_USUARI (CODI);

CREATE INDEX IPA_USUCRE_REGANXFIR_FK_I ON IPA_REGISTRE_ANNEX_FIRMA(CREATEDBY_CODI);
CREATE INDEX IPA_FIRMA_ANNEX_FK_I ON IPA_REGISTRE_ANNEX_FIRMA(ANNEX_ID);
CREATE INDEX IPA_USUMOD_REGANXFIR_FK_I ON IPA_REGISTRE_ANNEX_FIRMA(LASTMODIFIEDBY_CODI);