------------------------------------------------
-- Changes for table 'IPA_DOCUMENT_ENVIAMENT' --
------------------------------------------------

ALTER TABLE IPA_DOCUMENT_ENVIAMENT
    ALTER COLUMN ASSUMPTE TYPE character varying(50),
    ALTER COLUMN ASSUMPTE SET NOT NULL;
ALTER TABLE IPA_DOCUMENT_ENVIAMENT
    ALTER COLUMN OBSERVACIONS TYPE character varying(100);

ALTER TABLE IPA_DOCUMENT_ENVIAMENT ADD CADUCITAT timestamp without time zone;
ALTER TABLE IPA_DOCUMENT_ENVIAMENT ADD EMISOR_DIR3CODI character varying(9) NOT NULL;
ALTER TABLE IPA_DOCUMENT_ENVIAMENT ADD ENV_DATA_PROG timestamp without time zone;
ALTER TABLE IPA_DOCUMENT_ENVIAMENT ADD ENV_TIPUS character varying(50)   NOT NULL;
ALTER TABLE IPA_DOCUMENT_ENVIAMENT ADD DESTINATARI_NOM character varying(100);
ALTER TABLE IPA_DOCUMENT_ENVIAMENT ADD DESTINATARI_LLINATGE1 character varying(100);
ALTER TABLE IPA_DOCUMENT_ENVIAMENT ADD DESTINATARI_LLINATGE2 character varying(100);
ALTER TABLE IPA_DOCUMENT_ENVIAMENT ADD DESTINATARI_NIF character varying(9);
ALTER TABLE IPA_DOCUMENT_ENVIAMENT ADD DESTINATARI_TELEFON character varying(16);
ALTER TABLE IPA_DOCUMENT_ENVIAMENT ADD DESTINATARI_EMAIL character varying(100);
ALTER TABLE IPA_DOCUMENT_ENVIAMENT ADD DEH_OBLIGAT boolean;
ALTER TABLE IPA_DOCUMENT_ENVIAMENT ADD DEH_NIF character varying(9);
ALTER TABLE IPA_DOCUMENT_ENVIAMENT ADD NOTIFICA_REF character varying(20);
ALTER TABLE IPA_DOCUMENT_ENVIAMENT ADD SERVEI_TIPUS character varying(50);
ALTER TABLE IPA_DOCUMENT_ENVIAMENT ADD TITULAR_NOM character varying(100);
ALTER TABLE IPA_DOCUMENT_ENVIAMENT ADD TITULAR_LLINATGE1 character varying(100);
ALTER TABLE IPA_DOCUMENT_ENVIAMENT ADD TITULAR_LLINATGE2 character varying(100);
ALTER TABLE IPA_DOCUMENT_ENVIAMENT ADD TITULAR_NIF character varying(9) NOT NULL;
ALTER TABLE IPA_DOCUMENT_ENVIAMENT ADD TITULAR_TELEFON character varying(16);
ALTER TABLE IPA_DOCUMENT_ENVIAMENT ADD TITULAR_EMAIL character varying(100);
ALTER TABLE IPA_DOCUMENT_ENVIAMENT ADD PAGCIE_DIR3 character varying(9);
ALTER TABLE IPA_DOCUMENT_ENVIAMENT ADD PAGCIE_DATA_VIG timestamp without time zone;
ALTER TABLE IPA_DOCUMENT_ENVIAMENT ADD PAGCOR_DIR3 character varying(9);
ALTER TABLE IPA_DOCUMENT_ENVIAMENT ADD PAGCOR_NUMCONT character varying(20);
ALTER TABLE IPA_DOCUMENT_ENVIAMENT ADD PAGCOR_CODI_CLIENT character varying(20);
ALTER TABLE IPA_DOCUMENT_ENVIAMENT ADD PAGCOR_DATA_VIG timestamp without time zone;
ALTER TABLE IPA_DOCUMENT_ENVIAMENT ADD SEU_EXP_SERDOC character varying(10) NOT NULL;
ALTER TABLE IPA_DOCUMENT_ENVIAMENT ADD SEU_EXP_UNIORG character varying(10) NOT NULL;
ALTER TABLE IPA_DOCUMENT_ENVIAMENT ADD SEU_EXP_IDENI character varying(52) NOT NULL;
ALTER TABLE IPA_DOCUMENT_ENVIAMENT ADD SEU_EXP_TITOL character varying(256) NOT NULL;
ALTER TABLE IPA_DOCUMENT_ENVIAMENT ADD SEU_REG_OFICINA character varying(256) NOT NULL;
ALTER TABLE IPA_DOCUMENT_ENVIAMENT ADD SEU_REG_LLIBRE character varying(256) NOT NULL;
ALTER TABLE IPA_DOCUMENT_ENVIAMENT ADD SEU_AVIS_TITOL character varying(256) NOT NULL;
ALTER TABLE IPA_DOCUMENT_ENVIAMENT ADD SEU_AVIS_TEXT character varying(256) NOT NULL;
ALTER TABLE IPA_DOCUMENT_ENVIAMENT ADD SEU_AVIS_MOBIL character varying(256);
ALTER TABLE IPA_DOCUMENT_ENVIAMENT ADD SEU_OFICI_TITOL character varying(256) NOT NULL;
ALTER TABLE IPA_DOCUMENT_ENVIAMENT ADD SEU_OFICI_TEXT character varying(256) NOT NULL;
ALTER TABLE IPA_DOCUMENT_ENVIAMENT ADD PROC_CODI_SIA character varying(6) NOT NULL;
ALTER TABLE IPA_DOCUMENT_ENVIAMENT ADD RETARD_POSTAL integer;
ALTER TABLE IPA_DOCUMENT_ENVIAMENT ADD DOC_HASH character varying(40) NOT NULL;
ALTER TABLE IPA_DOCUMENT_ENVIAMENT ADD DOC_NORMALITZAT boolean;
ALTER TABLE IPA_DOCUMENT_ENVIAMENT ADD DOC_GEN_CSV boolean;


ALTER TABLE IPA_DOCUMENT_ENVIAMENT DROP COLUMN REGISTRE_NUM;
ALTER TABLE IPA_DOCUMENT_ENVIAMENT DROP COLUMN DESTIN_DOCNUM;
ALTER TABLE IPA_DOCUMENT_ENVIAMENT DROP COLUMN DESTIN_NOM;
ALTER TABLE IPA_DOCUMENT_ENVIAMENT DROP COLUMN DESTIN_LLING1;
ALTER TABLE IPA_DOCUMENT_ENVIAMENT DROP COLUMN DESTIN_LLING2;
ALTER TABLE IPA_DOCUMENT_ENVIAMENT DROP COLUMN DESTIN_EMAIL;
ALTER TABLE IPA_DOCUMENT_ENVIAMENT DROP COLUMN AVIS_TITOL;
ALTER TABLE IPA_DOCUMENT_ENVIAMENT DROP COLUMN AVIS_TEXT;
ALTER TABLE IPA_DOCUMENT_ENVIAMENT DROP COLUMN AVIS_TEXTSMS;
ALTER TABLE IPA_DOCUMENT_ENVIAMENT DROP COLUMN OFICI_TITOL;
ALTER TABLE IPA_DOCUMENT_ENVIAMENT DROP COLUMN OFICI_TEXT;


----------------------------------------
-- Changes for table 'IPA_INTERESSAT' --
----------------------------------------

ALTER TABLE IPA_INTERESSAT ADD DOM_TIPUS character varying(30);
ALTER TABLE IPA_INTERESSAT ADD DOM_APARTAT character varying(10);
ALTER TABLE IPA_INTERESSAT ADD DOM_BLOC character varying(50);
ALTER TABLE IPA_INTERESSAT ADD DOM_CIE integer;
ALTER TABLE IPA_INTERESSAT ADD DOM_CODI_POSTAL character varying(10);
ALTER TABLE IPA_INTERESSAT ADD DOM_COMPLEM character varying(250);
ALTER TABLE IPA_INTERESSAT ADD DOM_ESCALA character varying(50);
ALTER TABLE IPA_INTERESSAT ADD DOM_LINEA1 character varying(50);
ALTER TABLE IPA_INTERESSAT ADD DOM_LINEA2 character varying(50);
ALTER TABLE IPA_INTERESSAT ADD DOM_MUN_CODINE character varying(5);
ALTER TABLE IPA_INTERESSAT ADD DOM_NUM_TIPUS character varying(30);
ALTER TABLE IPA_INTERESSAT ADD DOM_NUM_NUM character varying(10);
ALTER TABLE IPA_INTERESSAT ADD DOM_PAI_CODISO character varying(3);
ALTER TABLE IPA_INTERESSAT ADD DOM_PLANTA character varying(50);
ALTER TABLE IPA_INTERESSAT ADD DOM_POBLACIO character varying(30);
ALTER TABLE IPA_INTERESSAT ADD DOM_PORTA character varying(50);
ALTER TABLE IPA_INTERESSAT ADD DOM_PORTAL character varying(50);
ALTER TABLE IPA_INTERESSAT ADD DOM_PRV_CODI character varying(2);
ALTER TABLE IPA_INTERESSAT ADD DOM_NUM_PUNTKM character varying(10);
ALTER TABLE IPA_INTERESSAT ADD DOM_VIA_NOM character varying(100);
ALTER TABLE IPA_INTERESSAT ADD DOM_VIA_TIPUS character varying(50);

ALTER TABLE IPA_INTERESSAT DROP COLUMN PAIS;
ALTER TABLE IPA_INTERESSAT DROP COLUMN PROVINCIA;
ALTER TABLE IPA_INTERESSAT DROP COLUMN MUNICIPI;
ALTER TABLE IPA_INTERESSAT DROP COLUMN ADRESA;
ALTER TABLE IPA_INTERESSAT DROP COLUMN CODI_POSTAL;

