
package es.caib.bantel.ws.v2.services;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import es.caib.bantel.ws.v2.model.referenciaentrada.ReferenciaEntrada;
import es.caib.bantel.ws.v2.model.referenciaentrada.ReferenciasEntrada;
import es.caib.bantel.ws.v2.model.tramitebte.TramiteBTE;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.2
 * 
 */
@WebService(name = "BackofficeFacade", targetNamespace = "urn:es:caib:bantel:ws:v2:services")
@XmlSeeAlso({
    es.caib.bantel.ws.v2.model.backofficefacade.ObjectFactory.class,
    es.caib.bantel.ws.v2.model.datosdocumentopresencial.ObjectFactory.class,
    es.caib.bantel.ws.v2.model.datosdocumentotelematico.ObjectFactory.class,
    es.caib.bantel.ws.v2.model.documentobte.ObjectFactory.class,
    es.caib.bantel.ws.v2.model.firmaws.ObjectFactory.class,
    es.caib.bantel.ws.v2.model.referenciaentrada.ObjectFactory.class,
    es.caib.bantel.ws.v2.model.tramitebte.ObjectFactory.class
})
public interface BackofficeFacade {


    /**
     * 
     * @param identificadorTramite
     * @param procesada
     * @param identificadorProcedimiento
     * @param hasta
     * @param desde
     * @return
     *     returns es.caib.bantel.ws.v2.model.referenciaentrada.ReferenciasEntrada
     * @throws BackofficeFacadeException
     */
    @WebMethod
    @WebResult(name = "obtenerNumerosEntradasReturn", targetNamespace = "urn:es:caib:bantel:ws:v2:model:BackofficeFacade")
    @RequestWrapper(localName = "obtenerNumerosEntradas", targetNamespace = "urn:es:caib:bantel:ws:v2:model:BackofficeFacade", className = "es.caib.bantel.ws.v2.model.backofficefacade.ObtenerNumerosEntradas")
    @ResponseWrapper(localName = "obtenerNumerosEntradasResponse", targetNamespace = "urn:es:caib:bantel:ws:v2:model:BackofficeFacade", className = "es.caib.bantel.ws.v2.model.backofficefacade.ObtenerNumerosEntradasResponse")
    public ReferenciasEntrada obtenerNumerosEntradas(
        @WebParam(name = "identificadorProcedimiento", targetNamespace = "urn:es:caib:bantel:ws:v2:model:BackofficeFacade")
        String identificadorProcedimiento,
        @WebParam(name = "identificadorTramite", targetNamespace = "urn:es:caib:bantel:ws:v2:model:BackofficeFacade")
        String identificadorTramite,
        @WebParam(name = "procesada", targetNamespace = "urn:es:caib:bantel:ws:v2:model:BackofficeFacade")
        String procesada,
        @WebParam(name = "desde", targetNamespace = "urn:es:caib:bantel:ws:v2:model:BackofficeFacade")
        XMLGregorianCalendar desde,
        @WebParam(name = "hasta", targetNamespace = "urn:es:caib:bantel:ws:v2:model:BackofficeFacade")
        XMLGregorianCalendar hasta)
        throws BackofficeFacadeException
    ;

    /**
     * 
     * @param numeroEntrada
     * @param resultado
     * @param resultadoProcesamiento
     * @throws BackofficeFacadeException
     */
    @WebMethod
    @RequestWrapper(localName = "establecerResultadoProceso", targetNamespace = "urn:es:caib:bantel:ws:v2:model:BackofficeFacade", className = "es.caib.bantel.ws.v2.model.backofficefacade.EstablecerResultadoProceso")
    @ResponseWrapper(localName = "establecerResultadoProcesoResponse", targetNamespace = "urn:es:caib:bantel:ws:v2:model:BackofficeFacade", className = "es.caib.bantel.ws.v2.model.backofficefacade.EstablecerResultadoProcesoResponse")
    public void establecerResultadoProceso(
        @WebParam(name = "numeroEntrada", targetNamespace = "urn:es:caib:bantel:ws:v2:model:BackofficeFacade")
        ReferenciaEntrada numeroEntrada,
        @WebParam(name = "resultado", targetNamespace = "urn:es:caib:bantel:ws:v2:model:BackofficeFacade")
        String resultado,
        @WebParam(name = "resultadoProcesamiento", targetNamespace = "urn:es:caib:bantel:ws:v2:model:BackofficeFacade")
        String resultadoProcesamiento)
        throws BackofficeFacadeException
    ;

    /**
     * 
     * @param numeroEntrada
     * @return
     *     returns es.caib.bantel.ws.v2.model.tramitebte.TramiteBTE
     * @throws BackofficeFacadeException
     */
    @WebMethod
    @WebResult(name = "obtenerEntradaReturn", targetNamespace = "urn:es:caib:bantel:ws:v2:model:BackofficeFacade")
    @RequestWrapper(localName = "obtenerEntrada", targetNamespace = "urn:es:caib:bantel:ws:v2:model:BackofficeFacade", className = "es.caib.bantel.ws.v2.model.backofficefacade.ObtenerEntrada")
    @ResponseWrapper(localName = "obtenerEntradaResponse", targetNamespace = "urn:es:caib:bantel:ws:v2:model:BackofficeFacade", className = "es.caib.bantel.ws.v2.model.backofficefacade.ObtenerEntradaResponse")
    public TramiteBTE obtenerEntrada(
        @WebParam(name = "numeroEntrada", targetNamespace = "urn:es:caib:bantel:ws:v2:model:BackofficeFacade")
        ReferenciaEntrada numeroEntrada)
        throws BackofficeFacadeException
    ;

}
