
package es.caib.dir3caib.ws.unidad;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "Dir3CaibObtenerUnidadesWs", targetNamespace = "http://unidad.ws.dir3caib.caib.es/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Dir3CaibObtenerUnidadesWs {


    /**
     * 
     * @return
     *     returns javax.xml.datatype.XMLGregorianCalendar
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "obtenerFechaUltimaActualizacion", targetNamespace = "http://unidad.ws.dir3caib.caib.es/", className = "es.caib.dir3caib.ws.unidad.ObtenerFechaUltimaActualizacion")
    @ResponseWrapper(localName = "obtenerFechaUltimaActualizacionResponse", targetNamespace = "http://unidad.ws.dir3caib.caib.es/", className = "es.caib.dir3caib.ws.unidad.ObtenerFechaUltimaActualizacionResponse")
    public XMLGregorianCalendar obtenerFechaUltimaActualizacion();

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getVersionWs", targetNamespace = "http://unidad.ws.dir3caib.caib.es/", className = "es.caib.dir3caib.ws.unidad.GetVersionWs")
    @ResponseWrapper(localName = "getVersionWsResponse", targetNamespace = "http://unidad.ws.dir3caib.caib.es/", className = "es.caib.dir3caib.ws.unidad.GetVersionWsResponse")
    public String getVersionWs();

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getVersion", targetNamespace = "http://unidad.ws.dir3caib.caib.es/", className = "es.caib.dir3caib.ws.unidad.GetVersion")
    @ResponseWrapper(localName = "getVersionResponse", targetNamespace = "http://unidad.ws.dir3caib.caib.es/", className = "es.caib.dir3caib.ws.unidad.GetVersionResponse")
    public String getVersion();

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns es.caib.dir3caib.ws.unidad.UnidadTF
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "obtenerUnidad", targetNamespace = "http://unidad.ws.dir3caib.caib.es/", className = "es.caib.dir3caib.ws.unidad.ObtenerUnidad")
    @ResponseWrapper(localName = "obtenerUnidadResponse", targetNamespace = "http://unidad.ws.dir3caib.caib.es/", className = "es.caib.dir3caib.ws.unidad.ObtenerUnidadResponse")
    public UnidadTF obtenerUnidad(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        XMLGregorianCalendar arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        XMLGregorianCalendar arg2);

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.util.List<es.caib.dir3caib.ws.unidad.UnidadTF>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "obtenerArbolUnidades", targetNamespace = "http://unidad.ws.dir3caib.caib.es/", className = "es.caib.dir3caib.ws.unidad.ObtenerArbolUnidades")
    @ResponseWrapper(localName = "obtenerArbolUnidadesResponse", targetNamespace = "http://unidad.ws.dir3caib.caib.es/", className = "es.caib.dir3caib.ws.unidad.ObtenerArbolUnidadesResponse")
    public List<UnidadTF> obtenerArbolUnidades(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        XMLGregorianCalendar arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        XMLGregorianCalendar arg2);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<es.caib.dir3caib.ws.unidad.UnidadTF>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "obtenerArbolUnidadesDestinatarias", targetNamespace = "http://unidad.ws.dir3caib.caib.es/", className = "es.caib.dir3caib.ws.unidad.ObtenerArbolUnidadesDestinatarias")
    @ResponseWrapper(localName = "obtenerArbolUnidadesDestinatariasResponse", targetNamespace = "http://unidad.ws.dir3caib.caib.es/", className = "es.caib.dir3caib.ws.unidad.ObtenerArbolUnidadesDestinatariasResponse")
    public List<UnidadTF> obtenerArbolUnidadesDestinatarias(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
