
package es.caib.dir3caib.ws.unidad;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "Dir3CaibObtenerUnidadesWsService", targetNamespace = "http://unidad.ws.dir3caib.caib.es/", wsdlLocation = "file:/home/likewise-open/LIMIT_CECOMASA/josepg/Feina/tmp/wsimport/Dir3CaibObtenerUnidades.wsdl")
public class Dir3CaibObtenerUnidadesWsService
    extends Service
{

    private final static URL DIR3CAIBOBTENERUNIDADESWSSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(es.caib.dir3caib.ws.unidad.Dir3CaibObtenerUnidadesWsService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = es.caib.dir3caib.ws.unidad.Dir3CaibObtenerUnidadesWsService.class.getResource(".");
            url = new URL(baseUrl, "file:/home/likewise-open/LIMIT_CECOMASA/josepg/Feina/tmp/wsimport/Dir3CaibObtenerUnidades.wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'file:/home/likewise-open/LIMIT_CECOMASA/josepg/Feina/tmp/wsimport/Dir3CaibObtenerUnidades.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        DIR3CAIBOBTENERUNIDADESWSSERVICE_WSDL_LOCATION = url;
    }

    public Dir3CaibObtenerUnidadesWsService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Dir3CaibObtenerUnidadesWsService() {
        super(DIR3CAIBOBTENERUNIDADESWSSERVICE_WSDL_LOCATION, new QName("http://unidad.ws.dir3caib.caib.es/", "Dir3CaibObtenerUnidadesWsService"));
    }

    /**
     * 
     * @return
     *     returns Dir3CaibObtenerUnidadesWs
     */
    @WebEndpoint(name = "Dir3CaibObtenerUnidadesWs")
    public Dir3CaibObtenerUnidadesWs getDir3CaibObtenerUnidadesWs() {
        return super.getPort(new QName("http://unidad.ws.dir3caib.caib.es/", "Dir3CaibObtenerUnidadesWs"), Dir3CaibObtenerUnidadesWs.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Dir3CaibObtenerUnidadesWs
     */
    @WebEndpoint(name = "Dir3CaibObtenerUnidadesWs")
    public Dir3CaibObtenerUnidadesWs getDir3CaibObtenerUnidadesWs(WebServiceFeature... features) {
        return super.getPort(new QName("http://unidad.ws.dir3caib.caib.es/", "Dir3CaibObtenerUnidadesWs"), Dir3CaibObtenerUnidadesWs.class, features);
    }

}
