
package es.indra.portafirmasws.cws;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "CwsService", targetNamespace = "http://www.indra.es/portafirmasws/cws", wsdlLocation = "file:/home/likewise-open/LIMIT_CECOMASA/josepg/Feina/tmp/wsimport/CWS.wsdl")
public class CwsService
    extends Service
{

    private final static URL CWSSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(es.indra.portafirmasws.cws.CwsService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = es.indra.portafirmasws.cws.CwsService.class.getResource(".");
            url = new URL(baseUrl, "file:/home/likewise-open/LIMIT_CECOMASA/josepg/Feina/tmp/wsimport/CWS.wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'file:/home/likewise-open/LIMIT_CECOMASA/josepg/Feina/tmp/wsimport/CWS.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        CWSSERVICE_WSDL_LOCATION = url;
    }

    public CwsService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CwsService() {
        super(CWSSERVICE_WSDL_LOCATION, new QName("http://www.indra.es/portafirmasws/cws", "CwsService"));
    }

    /**
     * 
     * @return
     *     returns Cws
     */
    @WebEndpoint(name = "CWS")
    public Cws getCWS() {
        return super.getPort(new QName("http://www.indra.es/portafirmasws/cws", "CWS"), Cws.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Cws
     */
    @WebEndpoint(name = "CWS")
    public Cws getCWS(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.indra.es/portafirmasws/cws", "CWS"), Cws.class, features);
    }

}
