package es.caib.dir3caib;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.3.9
 * 2014-09-29T08:19:59.892+02:00
 * Generated source version: 2.3.9
 * 
 */
@WebServiceClient(name = "ObtenerUnidadesService", 
                  wsdlLocation = "file:/home/likewise-open/LIMIT_CECOMASA/josepg/Feina/workspaces/workspace-luna/ripea/ripea-plugin-impl/../ripea-plugin/src/main/resources/es/caib/ripea/plugin/unitat/ObtenerUnidadesImpl.wsdl",
                  targetNamespace = "http://www.caib.es/dir3caib") 
public class ObtenerUnidadesService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.caib.es/dir3caib", "ObtenerUnidadesService");
    public final static QName ObtenerUnidades = new QName("http://www.caib.es/dir3caib", "ObtenerUnidades");
    static {
        URL url = null;
        try {
            url = new URL("file:/home/likewise-open/LIMIT_CECOMASA/josepg/Feina/workspaces/workspace-luna/ripea/ripea-plugin-impl/../ripea-plugin/src/main/resources/es/caib/ripea/plugin/unitat/ObtenerUnidadesImpl.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(ObtenerUnidadesService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/home/likewise-open/LIMIT_CECOMASA/josepg/Feina/workspaces/workspace-luna/ripea/ripea-plugin-impl/../ripea-plugin/src/main/resources/es/caib/ripea/plugin/unitat/ObtenerUnidadesImpl.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public ObtenerUnidadesService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ObtenerUnidadesService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ObtenerUnidadesService() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns ObtenerUnidades
     */
    @WebEndpoint(name = "ObtenerUnidades")
    public ObtenerUnidades getObtenerUnidades() {
        return super.getPort(ObtenerUnidades, ObtenerUnidades.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ObtenerUnidades
     */
    @WebEndpoint(name = "ObtenerUnidades")
    public ObtenerUnidades getObtenerUnidades(WebServiceFeature... features) {
        return super.getPort(ObtenerUnidades, ObtenerUnidades.class, features);
    }

}
