
package es.caib.ripea.core.service.ws.callbackportafib;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "PortaFIBCallBackWsService", targetNamespace = "http://v1.server.callback.ws.portafib.caib.es/", wsdlLocation = "file:/home/likewise-open/LIMIT_CECOMASA/josepg/Feina/tmp/wsimport/PortaFIBCallBack_v1.wsdl")
public class PortaFIBCallBackWsService
    extends Service
{

    private final static URL PORTAFIBCALLBACKWSSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(PortaFIBCallBackWsService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = PortaFIBCallBackWsService.class.getResource(".");
            url = new URL(baseUrl, "file:/home/likewise-open/LIMIT_CECOMASA/josepg/Feina/tmp/wsimport/PortaFIBCallBack_v1.wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'file:/home/likewise-open/LIMIT_CECOMASA/josepg/Feina/tmp/wsimport/PortaFIBCallBack_v1.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        PORTAFIBCALLBACKWSSERVICE_WSDL_LOCATION = url;
    }

    public PortaFIBCallBackWsService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PortaFIBCallBackWsService() {
        super(PORTAFIBCALLBACKWSSERVICE_WSDL_LOCATION, new QName("http://v1.server.callback.ws.portafib.caib.es/", "PortaFIBCallBackWsService"));
    }

    /**
     * 
     * @return
     *     returns PortaFIBCallBackWs
     */
    @WebEndpoint(name = "PortaFIBCallBackWs")
    public PortaFIBCallBackWs getPortaFIBCallBackWs() {
        return super.getPort(new QName("http://v1.server.callback.ws.portafib.caib.es/", "PortaFIBCallBackWs"), PortaFIBCallBackWs.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PortaFIBCallBackWs
     */
    @WebEndpoint(name = "PortaFIBCallBackWs")
    public PortaFIBCallBackWs getPortaFIBCallBackWs(WebServiceFeature... features) {
        return super.getPort(new QName("http://v1.server.callback.ws.portafib.caib.es/", "PortaFIBCallBackWs"), PortaFIBCallBackWs.class, features);
    }

}
