
package es.caib.ripea.core.service.ws.callbackportafib;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "PortaFIBCallBackWs", targetNamespace = "http://v1.server.callback.ws.portafib.caib.es/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface PortaFIBCallBackWs {


    /**
     * 
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getVersionWs", targetNamespace = "http://v1.server.callback.ws.portafib.caib.es/", className = "es.caib.portafib.ws.callback.server.v1.GetVersionWs")
    @ResponseWrapper(localName = "getVersionWsResponse", targetNamespace = "http://v1.server.callback.ws.portafib.caib.es/", className = "es.caib.portafib.ws.callback.server.v1.GetVersionWsResponse")
    public int getVersionWs();

    /**
     * 
     * @param event
     * @throws CallBackException
     */
    @WebMethod
    @RequestWrapper(localName = "event", targetNamespace = "http://v1.server.callback.ws.portafib.caib.es/", className = "es.caib.portafib.ws.callback.server.v1.Event")
    @ResponseWrapper(localName = "eventResponse", targetNamespace = "http://v1.server.callback.ws.portafib.caib.es/", className = "es.caib.portafib.ws.callback.server.v1.EventResponse")
    public void event(
        @WebParam(name = "event", targetNamespace = "")
        PortaFIBEvent event)
        throws CallBackException
    ;

}
