/**
 * 
 */
package es.caib.ripea.core.api.dto;


/**
 * Enumeració amb els possibles tipus d'accions de log.
 * 
 * @author Limit Tecnologies <limit@limit.es>
 */
public enum LogTipusEnumDto {
	CREACIO,
	CONSULTA,
	MODIFICACIO,
	ELIMINACIO,
	RECUPERACIO,
	ELIMINACIODEF,
	ACTIVACIO,
	DESACTIVACIO,
	AGAFAR,
	ALLIBERAR,
	COPIA,
	MOVIMENT,
	ENVIAMENT,
	REENVIAMENT,
	PROCESSAMENT,
	TANCAMENT,
	REOBERTURA,
	ACUMULACIO,
	DISGREGACIO,
	PER_DEFECTE,
	PFIRMA_ENVIAMENT,
	PFIRMA_CANCELACIO,
	PFIRMA_CALLBACK,
	PFIRMA_FIRMA,
	PFIRMA_REBUIG,
	PFIRMA_REINTENT,
	ARXIU_CSV,
	ARXIU_CUSTODIAT,
	CUSTODIA_CANCELACIO,
	FIRMA_CLIENT,
	NOTIFICACIO_ENTREGADA,
	NOTIFICACIO_REBUTJADA,
	NOTIFICACIO_REINTENT
}
