
DROP TABLE IPA_DOCUMENT_ENVIAMENT_DOC;
DROP TABLE IPA_DOCUMENT_ENVIAMENT;
CREATE TABLE IPA_DOCUMENT_ENVIAMENT
(
  ID                   NUMBER(19)               NOT NULL,
  DTYPE                VARCHAR2(32)             NOT NULL,
  ESTAT                VARCHAR2(255)            NOT NULL,
  ASSUMPTE             VARCHAR2(256)            NOT NULL,
  OBSERVACIONS         VARCHAR2(256),
  ENVIAT_DATA          TIMESTAMP(6),
  PROCESSAT_DATA       TIMESTAMP(6),
  CANCELAT_DATA        TIMESTAMP(6),
  ERROR                NUMBER(1),
  ERROR_DESC           VARCHAR2(255),
  INTENT_NUM           NUMBER(10),
  INTENT_DATA          TIMESTAMP(6),
  INTENT_PROXIM_DATA   TIMESTAMP(6),
  NOT_TIPUS            NUMBER(10),
  NOT_DATA_PROG        TIMESTAMP(6),
  NOT_RETARD           NUMBER(10),
  NOT_DATA_CADUCITAT   TIMESTAMP(6),
  NOT_INTERESSAT_ID    NUMBER(19),
  NOT_SEU_IDIOMA       VARCHAR2(2),
  NOT_SEU_AVIS_TITOL   VARCHAR2(256), 
  NOT_SEU_AVIS_TEXT    VARCHAR2(1024),
  NOT_SEU_AVIS_TEXTM   VARCHAR2(200),
  NOT_SEU_OFICI_TITOL  VARCHAR2(256),
  NOT_SEU_OFICI_TEXT   VARCHAR2(1024),
  NOT_ENV_ID           VARCHAR2(100),
  NOT_ENV_REF          VARCHAR2(100),
  NOT_ENV_DAT_ESTAT    VARCHAR2(20),
  NOT_ENV_DAT_DATA     TIMESTAMP(6),
  NOT_ENV_DAT_ORIG     VARCHAR2(20),
  NOT_ENV_CERT_DATA    TIMESTAMP(6),
  NOT_ENV_CERT_ORIG    VARCHAR2(20),
  PF_PRIORITAT         NUMBER(10),
  PF_CAD_DATA          TIMESTAMP(6),
  PF_DOC_TIPUS         VARCHAR2(64),
  PF_RESPONSABLES      VARCHAR2(1024),
  PF_FLUX_TIPUS        NUMBER(10),
  PF_FLUX_ID           VARCHAR2(64),
  PF_PORTAFIRMES_ID    VARCHAR2(64),
  PF_CALLBACK_ESTAT    NUMBER(10),
  PUB_TIPUS            NUMBER(10),
  DOCUMENT_ID          NUMBER(19)               NOT NULL,
  EXPEDIENT_ID         NUMBER(19)               NOT NULL,
  CREATEDDATE          TIMESTAMP(6),
  LASTMODIFIEDDATE     TIMESTAMP(6),
  CREATEDBY_CODI       VARCHAR2(256),
  LASTMODIFIEDBY_CODI  VARCHAR2(256),
  VERSION              NUMBER(19)               NOT NULL
);
CREATE TABLE IPA_DOCUMENT_ENVIAMENT_DOC (
  DOCUMENT_ENVIAMENT_ID NUMBER(19)              NOT NULL,
  DOCUMENT_ID           NUMBER(19)              NOT NULL
);
ALTER TABLE IPA_DOCUMENT_ENVIAMENT ADD (
  CONSTRAINT IPA_DOCENV_PK PRIMARY KEY (ID),
  CONSTRAINT IPA_DOCENV_MULT_UK UNIQUE (EXPEDIENT_ID, DOCUMENT_ID, ASSUMPTE, ENVIAT_DATA, DTYPE));
ALTER TABLE IPA_DOCUMENT_ENVIAMENT_DOC ADD (
  CONSTRAINT IPA_DOCUMENT_ENVDOC_PK PRIMARY KEY (DOCUMENT_ENVIAMENT_ID, DOCUMENT_ID));
ALTER TABLE IPA_DOCUMENT_ENVIAMENT ADD (
  CONSTRAINT IPA_EXPEDIENT_DOCENV_FK FOREIGN KEY (EXPEDIENT_ID) 
    REFERENCES IPA_EXPEDIENT (ID),
  CONSTRAINT IPA_DOCUMENT_DOCENV_FK FOREIGN KEY (DOCUMENT_ID) 
    REFERENCES IPA_DOCUMENT (ID),
  CONSTRAINT IPA_USUCRE_DOCENV_FK FOREIGN KEY (CREATEDBY_CODI) 
    REFERENCES IPA_USUARI (CODI),
  CONSTRAINT IPA_USUMOD_DOCENV_FK FOREIGN KEY (LASTMODIFIEDBY_CODI) 
    REFERENCES IPA_USUARI (CODI));
ALTER TABLE IPA_DOCUMENT_ENVIAMENT_DOC ADD (
  CONSTRAINT IPA_DOCUMENT_ENVDOC_DOCENV_FK FOREIGN KEY (DOCUMENT_ENVIAMENT_ID) 
    REFERENCES IPA_DOCUMENT_ENVIAMENT (ID),
  CONSTRAINT IPA_DOCUMENT_ENVDOC_DOC_FK FOREIGN KEY (DOCUMENT_ID) 
    REFERENCES IPA_DOCUMENT (ID));

ALTER TABLE IPA_METAEXPEDIENT RENAME COLUMN CLASIF_DOC TO SERIE_DOC;
ALTER TABLE IPA_METAEXPEDIENT DROP COLUMN UNITAT_ADM;
ALTER TABLE IPA_METAEXPEDIENT DROP COLUMN UNITAT_ADM_DESC;
ALTER TABLE IPA_METAEXPEDIENT RENAME COLUMN NOTIF_ACTIVA TO NOT_ACTIVA;
ALTER TABLE IPA_METAEXPEDIENT RENAME COLUMN NOTIF_UNITAT_ADM TO NOT_SEU_EXP_UNI;
ALTER TABLE IPA_METAEXPEDIENT RENAME COLUMN NOTIF_ORGAN_CODI TO NOT_SEU_REG_ORG;
ALTER TABLE IPA_METAEXPEDIENT RENAME COLUMN NOTIF_LLIBRE_CODI TO NOT_SEU_REG_LIB;
ALTER TABLE IPA_METAEXPEDIENT RENAME COLUMN NOTIF_AVIS_TITOL TO NOT_AVIS_TITOL;
ALTER TABLE IPA_METAEXPEDIENT RENAME COLUMN NOTIF_AVIS_TEXT TO NOT_AVIS_TEXT;
ALTER TABLE IPA_METAEXPEDIENT RENAME COLUMN NOTIF_AVIS_TEXTSMS TO NOT_AVIS_TEXTM;
ALTER TABLE IPA_METAEXPEDIENT RENAME COLUMN NOTIF_OFICI_TITOL TO NOT_OFICI_TITOL;
ALTER TABLE IPA_METAEXPEDIENT RENAME COLUMN NOTIF_OFICI_TEXT TO NOT_OFICI_TEXT;
ALTER TABLE IPA_METAEXPEDIENT ADD NOT_SEU_PROC_CODI VARCHAR2(44);
ALTER TABLE IPA_METAEXPEDIENT ADD NOT_SEU_REG_OFI VARCHAR2(9);

