ALTER TABLE IPA_METADOCUMENT ADD PROCEDIMENT_CODI_SIA VARCHAR2(256);
ALTER TABLE IPA_METADOCUMENT ADD SEU_EXP_SERIE_DOC VARCHAR2(256);


ALTER TABLE IPA_DOCUMENT_ENVIAMENT ADD CONCEPTE VARCHAR2(256);
ALTER TABLE IPA_DOCUMENT_ENVIAMENT ADD TIPUS_ENVIAMENT VARCHAR2(256);
ALTER TABLE IPA_DOCUMENT_ENVIAMENT ADD REFERENCIA VARCHAR2(64);
ALTER TABLE IPA_DOCUMENT_ENVIAMENT ADD ESTAT_DETALLAT VARCHAR2(255);


