CREATE TABLE IPA_REGISTRE_ANNEX_FIRMA
(
  ID                   NUMBER(19)               NOT NULL,
  TIPUS		           VARCHAR2(30),
  PERFIL    	       VARCHAR2(30),
  FITXER_NOM           VARCHAR2(80),
  TIPUS_MIME           VARCHAR2(30),
  CSV_REGULACIO		   VARCHAR2(640),
  ANNEX_ID             NUMBER(19)               NOT NULL,
  CREATEDDATE          TIMESTAMP(6),
  CREATEDBY_CODI       VARCHAR2(256),
  LASTMODIFIEDDATE     TIMESTAMP(6),
  LASTMODIFIEDBY_CODI  VARCHAR2(256)
);

ALTER TABLE IPA_REGISTRE_ANNEX_FIRMA ADD (
  CONSTRAINT IPA_REGANXFIR_PK PRIMARY KEY (ID));  

ALTER TABLE IPA_REGISTRE_ANNEX_FIRMA ADD (
  CONSTRAINT IPA_USUCRE_REGANXFIR_FK FOREIGN KEY (CREATEDBY_CODI) 
    REFERENCES IPA_USUARI (CODI),
  CONSTRAINT IPA_FIRMA_ANNEX_FK FOREIGN KEY (ANNEX_ID) 
    REFERENCES IPA_REGISTRE_ANNEX (ID),
  CONSTRAINT IPA_USUMOD_REGANXFIR_FK FOREIGN KEY (LASTMODIFIEDBY_CODI) 
    REFERENCES IPA_USUARI (CODI));

CREATE INDEX IPA_USUCRE_REGANXFIR_FK_I ON IPA_REGISTRE_ANNEX_FIRMA(CREATEDBY_CODI);
CREATE INDEX IPA_FIRMA_ANNEX_FK_I ON IPA_REGISTRE_ANNEX_FIRMA(ANNEX_ID);
CREATE INDEX IPA_USUMOD_REGANXFIR_FK_I ON IPA_REGISTRE_ANNEX_FIRMA(LASTMODIFIEDBY_CODI);

GRANT SELECT, UPDATE, INSERT, DELETE ON IPA_REGISTRE_ANNEX_FIRMA TO WWW_RIPEA;