CREATE TABLE IPA_CONT_COMMENT
(
  ID                   NUMBER(19)               NOT NULL,
  CONTINGUT_ID         NUMBER(19) 				NOT NULL,
  TEXT				   VARCHAR2 (1024),
  CREATEDDATE          TIMESTAMP(6),
  LASTMODIFIEDDATE     TIMESTAMP(6),
  CREATEDBY_CODI       VARCHAR2(64),
  LASTMODIFIEDBY_CODI  VARCHAR2(64)
);

ALTER TABLE IPA_CONT_COMMENT ADD (
  CONSTRAINT IPA_CONTCOMMENT_PK PRIMARY KEY (ID));

ALTER TABLE IPA_CONT_COMMENT ADD (
  CONSTRAINT IPA_CONT_CONTCOMMENT_FK FOREIGN KEY (CONTINGUT_ID) 
    REFERENCES IPA_CONTINGUT (ID),
  CONSTRAINT IPA_USUCRE_CONTCOMMENT_FK FOREIGN KEY (CREATEDBY_CODI) 
    REFERENCES IPA_USUARI (CODI),
  CONSTRAINT IPA_USUMOD_CONTCOMMENT_FK FOREIGN KEY (LASTMODIFIEDBY_CODI) 
    REFERENCES IPA_USUARI (CODI));

GRANT SELECT, UPDATE, INSERT, DELETE ON IPA_CONT_COMMENT TO WWW_RIPEA;