------------------------------------------------
-- Changes for table 'IPA_DOCUMENT_ENVIAMENT' --
------------------------------------------------

ALTER TABLE IPA_DOCUMENT_ENVIAMENT MODIFY (ASSUMPTE VARCHAR2(50) NOT NULL);
ALTER TABLE IPA_DOCUMENT_ENVIAMENT MODIFY (OBSERVACIONS VARCHAR2(100));

ALTER TABLE IPA_DOCUMENT_ENVIAMENT ADD CADUCITAT TIMESTAMP(6);
ALTER TABLE IPA_DOCUMENT_ENVIAMENT ADD EMISOR_DIR3CODI VARCHAR2(9) NOT NULL;
ALTER TABLE IPA_DOCUMENT_ENVIAMENT ADD ENV_DATA_PROG TIMESTAMP(6);
ALTER TABLE IPA_DOCUMENT_ENVIAMENT ADD ENV_TIPUS VARCHAR2(50) NOT NULL;
ALTER TABLE IPA_DOCUMENT_ENVIAMENT ADD DESTINATARI_NOM VARCHAR2(100);
ALTER TABLE IPA_DOCUMENT_ENVIAMENT ADD DESTINATARI_LLINATGE1 VARCHAR2(100);
ALTER TABLE IPA_DOCUMENT_ENVIAMENT ADD DESTINATARI_LLINATGE2 VARCHAR2(100);
ALTER TABLE IPA_DOCUMENT_ENVIAMENT ADD DESTINATARI_NIF VARCHAR2(9);
ALTER TABLE IPA_DOCUMENT_ENVIAMENT ADD DESTINATARI_TELEFON VARCHAR2(16);
ALTER TABLE IPA_DOCUMENT_ENVIAMENT ADD DESTINATARI_EMAIL VARCHAR2(100);
ALTER TABLE IPA_DOCUMENT_ENVIAMENT ADD DEH_OBLIGAT NUMBER(1);
ALTER TABLE IPA_DOCUMENT_ENVIAMENT ADD DEH_NIF VARCHAR2(9);
ALTER TABLE IPA_DOCUMENT_ENVIAMENT ADD NOTIFICA_REF VARCHAR2(20);
ALTER TABLE IPA_DOCUMENT_ENVIAMENT ADD SERVEI_TIPUS VARCHAR2(50);
ALTER TABLE IPA_DOCUMENT_ENVIAMENT ADD TITULAR_NOM VARCHAR2(100);
ALTER TABLE IPA_DOCUMENT_ENVIAMENT ADD TITULAR_LLINATGE1 VARCHAR2(100);
ALTER TABLE IPA_DOCUMENT_ENVIAMENT ADD TITULAR_LLINATGE2 VARCHAR2(100);
ALTER TABLE IPA_DOCUMENT_ENVIAMENT ADD TITULAR_NIF VARCHAR2(9) NOT NULL;
ALTER TABLE IPA_DOCUMENT_ENVIAMENT ADD TITULAR_TELEFON VARCHAR2(16);
ALTER TABLE IPA_DOCUMENT_ENVIAMENT ADD TITULAR_EMAIL VARCHAR2(100);
ALTER TABLE IPA_DOCUMENT_ENVIAMENT ADD PAGCIE_DIR3 VARCHAR2(9);
ALTER TABLE IPA_DOCUMENT_ENVIAMENT ADD PAGCIE_DATA_VIG TIMESTAMP(6);
ALTER TABLE IPA_DOCUMENT_ENVIAMENT ADD PAGCOR_DIR3 VARCHAR2(9);
ALTER TABLE IPA_DOCUMENT_ENVIAMENT ADD PAGCOR_NUMCONT VARCHAR2(20);
ALTER TABLE IPA_DOCUMENT_ENVIAMENT ADD PAGCOR_CODI_CLIENT VARCHAR2(20);
ALTER TABLE IPA_DOCUMENT_ENVIAMENT ADD PAGCOR_DATA_VIG TIMESTAMP(6);
ALTER TABLE IPA_DOCUMENT_ENVIAMENT ADD SEU_EXP_SERDOC VARCHAR2(10)             NOT NULL;
ALTER TABLE IPA_DOCUMENT_ENVIAMENT ADD SEU_EXP_UNIORG VARCHAR2(10)             NOT NULL;
ALTER TABLE IPA_DOCUMENT_ENVIAMENT ADD SEU_EXP_IDENI VARCHAR2(52)             NOT NULL;
ALTER TABLE IPA_DOCUMENT_ENVIAMENT ADD SEU_EXP_TITOL VARCHAR2(256)            NOT NULL;
ALTER TABLE IPA_DOCUMENT_ENVIAMENT ADD SEU_REG_OFICINA VARCHAR2(256)            NOT NULL;
ALTER TABLE IPA_DOCUMENT_ENVIAMENT ADD SEU_REG_LLIBRE VARCHAR2(256)            NOT NULL;
ALTER TABLE IPA_DOCUMENT_ENVIAMENT ADD SEU_AVIS_TITOL VARCHAR2(256)            NOT NULL;
ALTER TABLE IPA_DOCUMENT_ENVIAMENT ADD SEU_AVIS_TEXT VARCHAR2(256)            NOT NULL;
ALTER TABLE IPA_DOCUMENT_ENVIAMENT ADD SEU_AVIS_MOBIL VARCHAR2(256);
ALTER TABLE IPA_DOCUMENT_ENVIAMENT ADD SEU_OFICI_TITOL VARCHAR2(256)            NOT NULL;
ALTER TABLE IPA_DOCUMENT_ENVIAMENT ADD SEU_OFICI_TEXT VARCHAR2(256)            NOT NULL;
ALTER TABLE IPA_DOCUMENT_ENVIAMENT ADD PROC_CODI_SIA VARCHAR2(6)              NOT NULL;
ALTER TABLE IPA_DOCUMENT_ENVIAMENT ADD RETARD_POSTAL NUMBER(10);
ALTER TABLE IPA_DOCUMENT_ENVIAMENT ADD DOC_HASH VARCHAR2(40)             NOT NULL;
ALTER TABLE IPA_DOCUMENT_ENVIAMENT ADD DOC_NORMALITZAT NUMBER(1);
ALTER TABLE IPA_DOCUMENT_ENVIAMENT ADD DOC_GEN_CSV NUMBER(1);

ALTER TABLE IPA_DOCUMENT_ENVIAMENT DROP COLUMN registre_num;
ALTER TABLE IPA_DOCUMENT_ENVIAMENT DROP COLUMN destin_docnum;
ALTER TABLE IPA_DOCUMENT_ENVIAMENT DROP COLUMN destin_nom;
ALTER TABLE IPA_DOCUMENT_ENVIAMENT DROP COLUMN destin_lling1;
ALTER TABLE IPA_DOCUMENT_ENVIAMENT DROP COLUMN destin_lling2;
ALTER TABLE IPA_DOCUMENT_ENVIAMENT DROP COLUMN destin_email;
ALTER TABLE IPA_DOCUMENT_ENVIAMENT DROP COLUMN avis_titol;
ALTER TABLE IPA_DOCUMENT_ENVIAMENT DROP COLUMN avis_text;
ALTER TABLE IPA_DOCUMENT_ENVIAMENT DROP COLUMN avis_textsms;
ALTER TABLE IPA_DOCUMENT_ENVIAMENT DROP COLUMN ofici_titol;
ALTER TABLE IPA_DOCUMENT_ENVIAMENT DROP COLUMN ofici_text;


----------------------------------------
-- Changes for table 'IPA_INTERESSAT' --
----------------------------------------

ALTER TABLE IPA_INTERESSAT ADD DOM_TIPUS VARCHAR2(30);
ALTER TABLE IPA_INTERESSAT ADD DOM_APARTAT VARCHAR2(10);
ALTER TABLE IPA_INTERESSAT ADD DOM_BLOC VARCHAR2(50);
ALTER TABLE IPA_INTERESSAT ADD DOM_CIE NUMBER(10);
ALTER TABLE IPA_INTERESSAT ADD DOM_CODI_POSTAL VARCHAR2(10);
ALTER TABLE IPA_INTERESSAT ADD DOM_COMPLEM VARCHAR2(250);
ALTER TABLE IPA_INTERESSAT ADD DOM_ESCALA VARCHAR2(50);
ALTER TABLE IPA_INTERESSAT ADD DOM_LINEA1 VARCHAR2(50);
ALTER TABLE IPA_INTERESSAT ADD DOM_LINEA2 VARCHAR2(50);
ALTER TABLE IPA_INTERESSAT ADD DOM_MUN_CODINE VARCHAR2(5);
ALTER TABLE IPA_INTERESSAT ADD DOM_NUM_TIPUS VARCHAR2(30);
ALTER TABLE IPA_INTERESSAT ADD DOM_NUM_NUM VARCHAR2(10);
ALTER TABLE IPA_INTERESSAT ADD DOM_PAI_CODISO VARCHAR2(3);
ALTER TABLE IPA_INTERESSAT ADD DOM_PLANTA VARCHAR2(50);
ALTER TABLE IPA_INTERESSAT ADD DOM_POBLACIO VARCHAR2(30);
ALTER TABLE IPA_INTERESSAT ADD DOM_PORTA VARCHAR2(50);
ALTER TABLE IPA_INTERESSAT ADD DOM_PORTAL VARCHAR2(50);
ALTER TABLE IPA_INTERESSAT ADD DOM_PRV_CODI VARCHAR2(2);
ALTER TABLE IPA_INTERESSAT ADD DOM_NUM_PUNTKM VARCHAR2(10);
ALTER TABLE IPA_INTERESSAT ADD DOM_VIA_NOM VARCHAR2(100);
ALTER TABLE IPA_INTERESSAT ADD DOM_VIA_TIPUS VARCHAR2(50);

ALTER TABLE IPA_INTERESSATDROP COLUMN pais;
ALTER TABLE IPA_INTERESSATDROP COLUMN provincia;
ALTER TABLE IPA_INTERESSATDROP COLUMN municipi;
ALTER TABLE IPA_INTERESSATDROP COLUMN adresa;
ALTER TABLE IPA_INTERESSATDROP COLUMN codi_postal;


