
ALTER TABLE IPA_CONTINGUT ADD ARXIU_UUID VARCHAR2(36);
ALTER TABLE IPA_CONTINGUT ADD ARXIU_DATA_ACT TIMESTAMP(6);

ALTER TABLE IPA_CARPETA DROP COLUMN TIPUS;

ALTER TABLE IPA_DOCUMENT_VERSIO ADD ARXIU_UUID VARCHAR2(36);
UPDATE IPA_DOCUMENT_VERSIO SET ARXIU_UUID = ARXIU_GESDOC_ID;
ALTER TABLE IPA_DOCUMENT_VERSIO DROP COLUMN IPA_DOCUMENT_VERSIO;
