CREATE TABLE IPA_ALERTA
(
  ID                   NUMBER(19)               NOT NULL,
  TEXT                 VARCHAR2(256)            NOT NULL,
  ERROR                VARCHAR2(2048),
  LLEGIDA              NUMBER(1)                NOT NULL,
  CONTINGUT_ID         NUMBER(19),
  CREATEDBY_CODI       VARCHAR2(64),
  CREATEDDATE          TIMESTAMP(6),
  LASTMODIFIEDBY_CODI  VARCHAR2(64),
  LASTMODIFIEDDATE     TIMESTAMP(6)
);

ALTER TABLE IPA_ALERTA ADD (
  CONSTRAINT IPA_ALERTA_PK PRIMARY KEY (ID));
ALTER TABLE IPA_ALERTA ADD (
  CONSTRAINT IPA_CONTINGUT_ALERTA_FK FOREIGN KEY (CONTINGUT_ID) 
    REFERENCES IPA_CONTINGUT (ID),
  CONSTRAINT IPA_USUCRE_ALERTA_FK FOREIGN KEY (CREATEDBY_CODI) 
    REFERENCES IPA_USUARI (CODI),
  CONSTRAINT IPA_USUMOD_ALERTA_FK FOREIGN KEY (LASTMODIFIEDBY_CODI) 
    REFERENCES IPA_USUARI (CODI));
    
CREATE INDEX IPA_CONTINGUT_ALERTA_FK_I ON IPA_ALERTA(CONTINGUT_ID);
CREATE INDEX IPA_USUCRE_ALERTA_FK_I ON IPA_ALERTA(CREATEDBY_CODI);
CREATE INDEX IPA_USUMOD_ALERTA_FK_I ON IPA_ALERTA(LASTMODIFIEDBY_CODI);